FROM node:16-alpine

WORKDIR /usr/src/server

RUN apk add --no-cache dumb-init

COPY . .
ENV NODE_ENV development

RUN npm config set update-notifier false
RUN npm install

EXPOSE 3000
ENTRYPOINT [ "dumb-init", "npm", "run", "dev" ]