apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cerus-website
  name: cerus-website
  namespace: cerusbots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cerus-website
  template:
    metadata:
      labels:
        app: cerus-website
    spec:
      containers:
        - image: ghcr.io/cerusbots/website:master
          imagePullPolicy: Always
          name: website
          envFrom:
            - secretRef:
                name: cerus-website-secrets
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          ports:
            - containerPort: 3000
              name: http